name: Scheduler

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'
  push:
    branches: [main]
    paths:
      - 'sponsor.config.ts'
      - 'package.json'
      - '.github/workflows/scheduler.yml'

permissions:
  contents: write

jobs:
  update-sponsors:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install dependencies
        run: npm install

      - name: Update sponsors
        run: npm run build
        env:
          SPONSORKIT_GITHUB_TOKEN: ${{ secrets.SPONSORKIT_GITHUB_TOKEN }}
          SPONSORKIT_GITHUB_LOGIN: PeteBishwhip

      - name: Commit
        uses: EndBug/add-and-commit@v9
        with:
          author_name: GitHub Actions
          author_email: 41898282+github-actions[bot]@users.noreply.github.com
          message: 'chore: update sponsors.svg [ci skip]'
          add: 'sponsors.*'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
